# Generated by Django 3.2.4 on 2021-07-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintdetail',
            name='status',
            field=models.CharField(choices=[('On Going', 'On Going'), ('Closed', 'Closed'), ('Pending', 'Pending')], max_length=10),
        ),
    ]
