# Generated by Django 3.2.4 on 2021-07-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_complaintdetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintdetail',
            name='technician_assigned_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
