# Generated by Django 3.2.4 on 2021-07-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_complaintdetail_technician_assigned_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintdetail',
            name='status',
            field=models.CharField(choices=[('Just Arrived', 'Just Arrived'), ('On Going', 'On Going'), ('Closed', 'Closed'), ('Pending', 'Pending')], default='Just Arrived', max_length=20),
        ),
    ]
