# Generated by Django 3.2.4 on 2021-07-29 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_complaintdetail_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintdetail',
            name='technician_assigned_phone_number',
        ),
    ]
