# Generated by Django 3.2.4 on 2021-08-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_remove_complaintdetail_technician_assigned_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintdetail',
            name='technician_mobile',
            field=models.CharField(default='na', max_length=100),
        ),
    ]
